language: generic
sudo: false
cache:
  directories:
  - "$HOME/.stack"
notifications:
  email:
    on_success: change
    on_failure: change
addons:
  apt:
    packages:
    - libjpeg-turbo-progs
    - jpegoptim
before_install:
- travis_retry wget https://www.stackage.org/stack/linux-x86_64
- tar -xvf linux-x86_64
- mv stack-*-linux-x86_64/stack stack
script:
- export STACK="./stack --no-terminal"
- travis_retry $STACK setup
- "$STACK build"
- "$STACK exec site build || $STACK exec site rebuild"
deploy:
  provider: s3
  access_key_id: AKIAJ2C2R3QMVKSDOBXA
  secret_access_key:
    secure: JcBJ+i3j3SDRFDq95KbQi+H3hUYh3t0fLvbwXAbsRf7HVo69G60DaiN1nAQswtfI+LBXY2jtA/Fjlz9BfFv4TSmCxRJycL/FHNh6boCwLEMknHJrxfDMCAPdLdgWyzHhXIKL8rzSoS/3ptA/fXI93rysqPDadnHPV6Rd/ETVez9hNcmulkiWvpjDzleOuv54994AiVGDOPOH/GqdoclHw59XDVvp0Y6ioIj5JGQHoDT9I/THrB0oCEYV3yPW1qiPl7JcNhF5COCWsi+/7CbscjVKhXV2rK3tPqMUepDkxPLiFY4T65fPJbsZt5qiPUi1R+mCPU+nRlTzzgOg/3y30lR/kVCCKxRWU0zOg3nXrOjuq6zSHOHoUJvWwbIgk0IN+tRm8m8SpDvDssdGMBxKkaFqRxZGKcT/k8pgll29hctLETrUN2m6Xpy+tgv1VJIXWdIkP/uLgx8eAjWqWdJClkg2nfDn8phH/dBMWuAp30+SeHu17rh+C71Xeq7cOhEFrUvaR30R5ZjjJVIH/suW4Gr2gPQ0zgFAhjPXp7fy4Qsc9Gs6eqkbOa4nM0LW/2JvyMgSzDIetFgepsbOUjomTLsNDztfY7U+7rHrNJmXAlMi+41wjjoamw/OkMIL8bkm8SChSXX3r8z3igYa2vq7JO46B/5ES4RbzuH/s4x/VH8=
  region: ap-southeast-2
  bucket: passingcuriosity.com
  skip_cleanup: true
  local_dir: _site
  acl: public_read
  cache_control: public
  detect_encoding: true
  default_text_charset: utf-8
  on:
    branch: master
