
# Include Haskell tools
language: generic

# Use the docker infrastructure
sudo: false

# Cache the installed Haskell stuff
cache:
  directories:
    - $HOME/.stack

notifications:
  email:
    on_success: change
    on_failure: change

# Download the latest stack command.
before_install:
  - travis_retry wget https://www.stackage.org/stack/linux-x86_64
  - tar -xvf linux-x86_64
  - mv stack-*-linux-x86_64/stack stack

# Here starts the actual work to be performed for the package under test; any
# command which exits with a non-zero exit code causes the build to fail.
script:
 - export STACK="./stack --no-terminal"
 - travis_retry $STACK setup
 - $STACK build
 - $STACK exec site build || $STACK exec site rebuild

# Deploy built site to S3
deploy:
  provider: s3
  access_key_id: AKIAJ6M2UBGAPX7K7LQA
  secret_access_key:
    secure: R8wfmMZ4cCu3Ugm9ASGuoCbPrl/WEPaVlT1aKJ5JQYU1Xo4zSr5q4jpr/XD/zs5LG1G8y1hUnk2p2lmceSA5jF1v4aHeIRGLVM6yZbsDWTxDarFmgdHavC9W5q/Oe3QXylzoU7bZX5f/61BEudZ6mn1kb0TgHepY0IlHtMAJsGo=
  region: "ap-southeast-2"
  bucket: "passingcuriosity.com"
  skip_cleanup: true
  local_dir: "_site"
  acl: public_read
  cache_control: "public"
  detect_encoding: true
  default_text_charset: "utf-8"
  on:
    branch: master
